---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: summarize-api
  labels:
    app: summarize-api
spec:
  host: jira-summarizer.apps.platform-sts.pcbk.p1.openshiftapps.com
  to:
    kind: Service
    name: summarize-api
    weight: 100
  port:
    targetPort: 8000
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None

---
apiVersion: v1
kind: Service
metadata:
  name: summarize-api
spec:
  selector:
    app: summarize-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: summarize-api
  labels:
    app: summarize-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: summarize-api
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: summarize-api
    spec:
      containers:
        - name: summarize-api
          image: ghcr.io/johnstrunk/jira-summarizer:1.5.0@sha256:85ad7a19d32d23a32cf54d9f8c532a4596a85dff699d819f68f18adb289066e1
          command:
            - "/app/.venv/bin/gunicorn"
          args:
            - "--bind=0.0.0.0:8000"
            - "--access-logfile=-"
            # - "--workers=16"
            # - "--timeout=600"
            - "summarize_api:create_app()"
          envFrom:
            - secretRef:
                name: jira-summarizer-secret
                optional: false
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
      securityContext:
        runAsNonRoot: true
      terminationGracePeriodSeconds: 30
      volumes:
        - name: tmp-volume
          emptyDir: {}
