---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jira-estimator-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jira-estimator
  labels:
    app: jira-estimator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jira-estimator
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jira-estimator
    spec:
      containers:
        - name: estimator
          image: ghcr.io/johnstrunk/jira-summarizer@sha256:b0a534310bdbed6a2151820e31d1cd68297ec0c1935fc46176007ccfa0420c9e
          command:
            - "/app/.venv/bin/python"
            - "estimator.py"
          args:
            - "--log-level"
            - "INFO"
            - "--seconds"
            - "1800"
            - "--window"
            - "300"
            - "--output"
            - "/data/estimates.csv"
            - "--db-host"
            - "summarizer-db"
          envFrom:
            - secretRef:
                name: jira-summarizer-secret
                optional: false
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: data
              mountPath: "/data"
      securityContext:
        runAsNonRoot: true
      terminationGracePeriodSeconds: 5
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: jira-estimator-pvc
