---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jira-summarizer
  labels:
    app: jira-summarizer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jira-summarizer
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jira-summarizer
    spec:
      containers:
        - name: summarizer
          image: ghcr.io/johnstrunk/jira-summarizer@sha256:84e3ba59396a32cef3d526df7928f60084b75beaf6a5e2c72991332718692a1f
          args:
            - "--log-level"
            - "INFO"
            - "--seconds"
            - "120"
            - "--modified-since"
            - "2024-06-03"
          envFrom:
            - secretRef:
                name: jira-summarizer-secret
                optional: false
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
      securityContext:
        runAsNonRoot: true
      terminationGracePeriodSeconds: 5
