---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: summarizer-api
  labels:
    app: summarizer-api
spec:
  host: jira-summarizer.apps.platform-sts.pcbk.p1.openshiftapps.com
  to:
    kind: Service
    name: summarizer-api
    weight: 100
  port:
    targetPort: 8000
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None

---
apiVersion: v1
kind: Service
metadata:
  name: summarizer-api
spec:
  selector:
    app: summarizer-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: summarizer-api
  labels:
    app: summarizer-api
spec:
  replicas: 10
  selector:
    matchLabels:
      app: summarizer-api
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: summarizer-api
    spec:
      containers:
        - name: summarizer-api
          image: ghcr.io/johnstrunk/jira-summarizer@sha256:2232f18207ef06f918eb708ef82165e4d6bf08642d42ce3a9092c6ad4a161e39
          command:
            - "/app/.venv/bin/gunicorn"
          args:
            - "--bind=0.0.0.0:8000"
            - "--access-logfile=-"
            - "--timeout=60"
            - "summarize_api:create_app()"
          env:
            - name: MARIADB_HOST
              value: summarizer-db
          envFrom:
            - secretRef:
                name: jira-summarizer-secret
                optional: false
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 60
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
      securityContext:
        runAsNonRoot: true
      terminationGracePeriodSeconds: 30
      volumes:
        - name: tmp-volume
          emptyDir: {}
